USE rac_ar;

INSERT INTO
		rac_ar.cliente (id_cliente,nombre,apellido,documento,mail,calificacion,preferencias)
        VALUES
		(1,'Teddi','O  Connell',31191297,'TOConnell@mail.com',6,'Auto compacto para conducir en la ciudad- ideal para maniobras en espacios reducidos y con bajo consumo de combustible.'),
		(2,'Wittie','Fairholm',21153508,'WFairholm@mail.com',10,'Vehículo con capacidad para 7 pasajeros- ideal para viajes familiares o grupos grandes con amplio espacio de maletero.'),
		(3,'Reba','McDowell',20336101,'RMcDowell@mail.com',6,'Auto eléctrico con autonomía superior a 300 km- amigable con el medio ambiente y libre de emisiones contaminantes.'),
		(4,'Bernete','Sabey',15855111,'BSabey@mail.com',6,'SUV con tracción en las cuatro ruedas- perfecto para trayectos off-road o terrenos irregulares- con mayor seguridad.'),
		(5,'Bren','Pickthall',41277576,'BPickthall@mail.com',9,'Coche de lujo con interior de cuero y tecnología avanzada- ideal para eventos especiales o clientes que buscan máxima comodidad.'),
		(6,'Sidoney','Gaythwaite',39390240,'SGaythwaite@mail.com',6,'Vehículo con transmisión automática- para facilitar la conducción y evitar el cansancio en trayectos largos en la ciudad o carretera.'),
		(7,'Gustie','Windrus',31624126,'GWindrus@mail.com',8,'Auto híbrido con motor de combustión y eléctrico- para mayor eficiencia energética y ahorro en consumo de combustible.'),
		(8,'Estrellita','Cansfield',33623938,'ECansfield@mail.com',8,'Vehículo con amplio espacio de maletero- ideal para transportar equipaje o grandes volúmenes en viajes largos o mudanzas.'),
		(9,'Paige','McQuorkell',40351750,'PMcQuorkell@mail.com',7,'Auto deportivo con alta potencia- para los clientes que buscan una experiencia de conducción emocionante y de alto rendimiento.'),
		(10,'Cris','Playfair',15763469,'CPlayfair@mail.com',6,'Vehículo con asientos para niños instalados- ideal para familias con bebés o niños pequeños que necesitan seguridad adicional.'),
		(11,'Jerald','Feragh',19290964,'JFeragh@mail.com',6,'Coche con conexión Bluetooth y sistemas de entretenimiento avanzados- para disfrutar de música y llamadas en trayectos largos.'),
		(12,'Jeremy','Norley',23570503,'JNorley@mail.com',9,'Vehículo con GPS incorporado para facilitar la navegación en ciudades desconocidas o zonas rurales sin acceso a señal de celular.'),
		(13,'Jordain','Tuffell',25028758,'JTuffell@mail.com',9,'Auto con techo solar- para disfrutar de una mayor entrada de luz natural y una experiencia de conducción más placentera.'),
		(14,'Sherye','Alcalde',31094201,'SAlcalde@mail.com',6,'Vehículo con frenos ABS y control de estabilidad- para garantizar mayor seguridad y control en condiciones adversas de manejo.'),
		(15,'Yurik','Malkin',39303974,'YMalkin@mail.com',5,'Coche con cámaras de estacionamiento y sensores de proximidad- ideal para quienes desean mayor seguridad al estacionar.'),
		(16,'Chas','Vannoni',28418046,'CVannoni@mail.com',8,'Auto con asientos reclinables y climatización ajustable- para mayor confort en trayectos largos y climas extremos.'),
		(17,'Haleigh','Franies',33344616,'HFranies@mail.com',9,'Vehículo con faros automáticos y luces LED- para mejorar la visibilidad en carretera y proporcionar mayor seguridad.'),
		(18,'Iggy','Dilkes',26589173,'IDilkes@mail.com',10,'Auto con control crucero adaptativo- para mantener una velocidad constante en la carretera sin necesidad de acelerar manualmente.'),
		(19,'Brande','Leirmonth',36341041,'BLeirmonth@mail.com',8,'Vehículo con sistemas de asistencia de conducción- como alerta de cambio de carril y frenado automático en situaciones de emergencia.'),
		(20,'Brinn','Saddler',33867906,'BSaddler@mail.com',9,'Coche con ventanas polarizadas- ideal para mayor privacidad y protección contra la luz solar intensa en climas cálidos.'),
		(21,'Hall','Vuitton',32282489,'HVuitton@mail.com',8,'Auto con capacidad de remolque- perfecto para transportar caravanas- botes o cargas pesadas en viajes de larga distancia.'),
		(22,'Currey','Kahane',23819630,'CKahane@mail.com',10,'Vehículo con seguro contra todo riesgo incluido- para mayor tranquilidad del cliente en caso de accidentes o daños.'),
		(23,'Sarette','Salazar',37506709,'SSalazar@mail.com',5,'Auto con tapicería resistente a manchas- ideal para quienes viajan con niños o mascotas y buscan un vehículo fácil de limpiar.'),
		(24,'Rhody','Antonazzi',44273885,'RAntonazzi@mail.com',6,'Vehículo con sistema de climatización dual- para que tanto el conductor como el pasajero puedan ajustar la temperatura a su preferencia.'),
		(25,'Diarmid','Mawman',25911488,'DMawman@mail.com',7,'Coche con sistemas de ahorro de combustible- como el apagado automático del motor en detenciones prolongadas.'),
		(26,'Zitella','Davidsohn',24934053,'ZDavidsohn@mail.com',6,'Auto con asistencia en carretera 24/7- para mayor seguridad en caso de averías o accidentes en cualquier momento del día.'),
		(27,'Renaldo','Scranny',26761064,'RScranny@mail.com',10,'Vehículo con sistema de tracción inteligente- para mayor control en terrenos resbaladizos o durante condiciones climáticas adversas.'),
		(28,'Brianna','Burkert',35396489,'BBurkert@mail.com',9,'Auto con tecnología de frenado regenerativo- para aumentar la eficiencia energética en autos eléctricos o híbridos.'),
		(29,'Hazel','McDowall',15702791,'HMcDowall@mail.com',6,'Vehículo con conectores USB para cargar dispositivos móviles y mantener la conectividad durante trayectos largos.'),
		(30,'Brandais','Novacek',20148439,'BNovacek@mail.com',8,'Auto con capacidad para adaptar una silla de ruedas o espacio para personas con movilidad reducida.'),
		(31,'Saw','Anmore',34357191,'SAnmore@mail.com',8,'Vehículo con sistema de insonorización mejorado- para una experiencia de conducción más silenciosa y placentera.'),
		(32,'Seka','Assur',25906415,'SAssur@mail.com',8,'Auto con espejos retrovisores ajustables electrónicamente- para mayor comodidad y visibilidad al conducir.'),
		(33,'Clyve','Fletham',39323197,'CFletham@mail.com',6,'Vehículo con capacidad de plegar asientos traseros- para aumentar el espacio de almacenamiento según sea necesario.'),
		(34,'Jordon','Hallihan',40480156,'JHallihan@mail.com',8,'Coche con sistema de alerta de colisión frontal- para mayor seguridad en caso de acercarse demasiado a otro vehículo en carretera.'),
		(35,'Towney','Grinvalds',41188217,'TGrinvalds@mail.com',8,'Auto con sistema de monitoreo de punto ciego- para ayudar a evitar accidentes al cambiar de carril o estacionar.'),
		(36,'Katalin','Gleave',15391460,'KGleave@mail.com',7,'Vehículo con capacidad para integrar aplicaciones móviles- como Apple CarPlay o Android Auto- para una experiencia de manejo conectada.'),
		(37,'Julian','Rizzello',44243924,'JRizzello@mail.com',6,'Auto con parabrisas calefactado- ideal para zonas frías donde la nieve o el hielo pueden afectar la visibilidad.'),
		(38,'Pincas','Ulyat',30986149,'PUlyat@mail.com',8,'Vehículo con entrada sin llave y arranque a distancia- para mayor comodidad y seguridad al entrar y salir del auto.'),
		(39,'Kinnie','Schultheiss',35898460,'KSchultheiss@mail.com',6,'Coche con sistema de asistencia de estacionamiento automático- para facilitar el aparcamiento en espacios reducidos.'),
		(40,'Nani','Wooffitt',32210416,'NWooffitt@mail.com',6,'Auto con suspensión deportiva- para una experiencia de conducción más dinámica y ágil en carreteras con curvas.'),
		(41,'Jobi','Sigg',17716226,'JSigg@mail.com',6,'Vehículo con llantas todo terreno- para trayectos fuera de la carretera o en superficies con baja tracción.'),
		(42,'Savina','Luebbert',23710576,'SLuebbert@mail.com',9,'Auto con sistema de purificación de aire- ideal para personas con alergias o quienes desean aire más limpio dentro del vehículo.'),
		(43,'Marlon','Gegay',22443038,'MGegay@mail.com',8,'Vehículo con iluminación ambiental personalizable- para crear una atmósfera única y agradable durante la conducción nocturna.'),
		(44,'Reginauld','Kahler',35669529,'RKahler@mail.com',8,'Coche con sistema de control de presión de neumáticos- para alertar sobre posibles problemas en las ruedas y mejorar la seguridad.'),
		(45,'Rivkah','Yes',15018151,'RYes@mail.com',6,'Auto con sistema de frenado automático en reversa- para evitar colisiones al retroceder en espacios ajustados.'),
		(46,'Myrta','Cardenosa',43441165,'MCardenosa@mail.com',7,'Vehículo con asientos ventilados- ideal para climas cálidos donde el cuero o la tela pueden acumular calor.'),
		(47,'Chick','Frankiss',29606657,'CFrankiss@mail.com',10,'Auto con volante ajustable en altura y profundidad- para personalizar la posición de conducción según la preferencia del cliente.'),
		(48,'Bradney','Banbury',24785170,'BBanbury@mail.com',6,'Vehículo con sistema de sonido premium- para disfrutar de música y entretenimiento con la mejor calidad de audio.'),
		(49,'Joletta','Merriott',33543051,'JMerriott@mail.com',7,'Auto con capacidad para adaptar portaequipajes en el techo- ideal para quienes llevan equipos deportivos o grandes maletas.'),
		(50,'Martainn','Parmiter',41329900,'MParmiter@mail.com',5,'Vehículo con cargador inalámbrico para dispositivos móviles- para una mayor comodidad y conectividad sin cables.'),
		(51,'Jojo','Van der Kruijs',42945947,'JVan der Kruijs@mail.com',8,'Coche con limitador de velocidad ajustable- para evitar superar los límites de velocidad en zonas controladas.'),
		(52,'Glynnis','Oneil',26639056,'GOneil@mail.com',7,'Auto con tecnología de asistencia para subidas- para evitar que el coche ruede hacia atrás en pendientes pronunciadas.'),
		(53,'Bette-ann','Showt',20430557,'BShowt@mail.com',10,'Vehículo con cortinas laterales de aire- para mayor protección en caso de impactos laterales durante un accidente.'),
		(54,'Nevins','Hugk',36700535,'NHugk@mail.com',8,'Auto con espejos retrovisores con calefacción- para evitar que se empañen en climas fríos o lluviosos.'),
		(55,'Sayer','Hegdonne',34284833,'SHegdonne@mail.com',7,'Vehículo con freno de mano electrónico- para mayor facilidad y seguridad al estacionar en diferentes terrenos.'),
		(56,'Annelise','Okenden',36842453,'AOkenden@mail.com',6,'Coche con sistema de protección contra vuelcos- para mayor seguridad en carreteras con curvas o terrenos accidentados.'),
		(57,'Laurence','Haselup',34749768,'LHaselup@mail.com',5,'Auto con función de autoaparado- para mayor seguridad en zonas con mucho tráfico o durante maniobras complejas.'),
		(58,'Brig','Gould',22614205,'BGould@mail.com',9,'Vehículo con pantalla táctil de alta resolución- para facilitar el acceso a controles de navegación y entretenimiento.'),
		(59,'Shanan','Silk',19615541,'SSilk@mail.com',8,'Auto con sistema de reconocimiento de señales de tráfico- para alertar al conductor sobre cambios en los límites de velocidad o advertencias.'),
		(60,'Susan','Merton',41678181,'SMerton@mail.com',8,'Vehículo con sistema de gestión de batería avanzada- para maximizar la autonomía de autos eléctricos o híbridos.'),
		(61,'Gottfried','Skrine',31876737,'GSkrine@mail.com',9,'Auto con asientos de ajuste eléctrico con memoria- para facilitar el cambio de conductores sin perder la configuración preferida.'),
		(62,'Abe','Pregel',28056293,'APregel@mail.com',5,'Vehículo con sistema de monitoreo de fatiga del conductor- para alertar sobre posibles signos de cansancio al volante.'),
		(63,'Sheree','Brion',33561882,'SBrion@mail.com',6,'Auto con llantas de bajo perfil- para una conducción más deportiva y mejor respuesta en carreteras de alta velocidad.'),
		(64,'Brianna','Mersey',19671761,'BMersey@mail.com',6,'Vehículo con sistema de estabilización de remolque- para mayor seguridad al conducir con cargas pesadas o caravanas.'),
		(65,'Kelcey','Gowers',40820957,'KGowers@mail.com',6,'Coche con tapicería de cuero perforado- para una mejor ventilación y confort en climas cálidos o fríos.'),
		(66,'Aliza','Vasyutin',34401052,'AVasyutin@mail.com',9,'Auto con tecnología de regeneración de energía en frenado- para maximizar la eficiencia en vehículos híbridos y eléctricos.'),
		(67,'Francine','Dryden',21613734,'FDryden@mail.com',9,'Vehículo con luces adaptativas- que ajustan el haz de luz según las condiciones de la carretera y el entorno.'),
		(68,'Connor','De-Ville',18184938,'CDe-Ville@mail.com',7,'Coche con sistema de advertencia de tráfico cruzado trasero- para mayor seguridad al retroceder en estacionamientos o calles concurridas.'),
		(69,'Cart','Salmoni',26892954,'CSalmoni@mail.com',9,'Auto con sistema de control de estabilidad avanzada- para prevenir derrapes en superficies mojadas o resbaladizas.'),
		(70,'Terza','Jakubowsky',41949206,'TJakubowsky@mail.com',5,'Vehículo con asientos calefaccionados en todas las plazas- ideal para climas fríos donde se necesita mayor confort.'),
		(71,'Temp','Birtwisle',26319172,'TBirtwisle@mail.com',10,'Coche con sistema de dirección asistida eléctrica- para una maniobrabilidad más precisa y ahorro de combustible.'),
		(72,'Tybalt','Silverman',20561358,'TSilverman@mail.com',10,'Auto con puertas de cierre suave- que reducen el esfuerzo al cerrar y mejoran el confort en la experiencia de uso.'),
		(73,'Coretta','Agott',28155483,'CAgott@mail.com',8,'Vehículo con sistema de visión nocturna- para mejorar la visibilidad durante la conducción en condiciones de baja luz.'),
		(74,'Dasi','Tibbotts',18930673,'DTibbotts@mail.com',5,'Auto con sistema de reducción de emisiones- ideal para clientes preocupados por el impacto ambiental de sus trayectos.'),
		(75,'Terry','Tesh',29881295,'TTesh@mail.com',10,'Vehículo con parabrisas acústico- para reducir el ruido exterior y mejorar el confort de conducción en áreas urbanas o autopistas.'),
		(76,'Ed','Logsdail',39788899,'ELogsdail@mail.com',6,'Auto con capacidad para adaptar una silla de ruedas o espacio para personas con movilidad reducida.'),
		(77,'Alyson','Pull',30516802,'APull@mail.com',9,'Auto con espejos retrovisores con calefacción- para evitar que se empañen en climas fríos o lluviosos.'),
		(78,'Micheal','Foan',41292885,'MFoan@mail.com',10,'Coche con tapicería de cuero perforado- para una mejor ventilación y confort en climas cálidos o fríos.'),
		(79,'Mercy','Auchterlonie',31135264,'MAuchterlonie@mail.com',6,'Auto con espejos retrovisores ajustables electrónicamente- para mayor comodidad y visibilidad al conducir.'),
		(80,'Leonardo','Boas',24893607,'LBoas@mail.com',5,'Vehículo con llantas todo terreno- para trayectos fuera de la carretera o en superficies con baja tracción.'),
		(81,'Terrijo','Christal',26571422,'TChristal@mail.com',6,'Vehículo con asientos ventilados- ideal para climas cálidos donde el cuero o la tela pueden acumular calor.'),
		(82,'Deerdre','Leggan',43603797,'DLeggan@mail.com',7,'Vehículo con luces adaptativas- que ajustan el haz de luz según las condiciones de la carretera y el entorno.'),
		(83,'Magda','Fairhurst',30777380,'MFairhurst@mail.com',10,'Coche con sistemas de ahorro de combustible- como el apagado automático del motor en detenciones prolongadas.'),
		(84,'Jorrie','Faulo',32001826,'JFaulo@mail.com',10,'Vehículo con freno de mano electrónico- para mayor facilidad y seguridad al estacionar en diferentes terrenos.'),
		(85,'Tommi','Pleager',33818335,'TPleager@mail.com',9,'Coche con limitador de velocidad ajustable- para evitar superar los límites de velocidad en zonas controladas.'),
		(86,'Abrahan','Mc Carrick',31633630,'AMc Carrick@mail.com',9,'Auto con sistema de frenado automático en reversa- para evitar colisiones al retroceder en espacios ajustados.'),
		(87,'Ema','Lewens',18951477,'ELewens@mail.com',7,'Auto con suspensión deportiva- para una experiencia de conducción más dinámica y ágil en carreteras con curvas.'),
		(88,'Jany','Wycliffe',27520969,'JWycliffe@mail.com',6,'Auto con función de autoaparado- para mayor seguridad en zonas con mucho tráfico o durante maniobras complejas.'),
		(89,'Geoffry','Izakov',25863617,'GIzakov@mail.com',7,'Vehículo con sistema de insonorización mejorado- para una experiencia de conducción más silenciosa y placentera.'),
		(90,'Wendel','Edmand',26749383,'WEdmand@mail.com',7,'Vehículo con sistema de gestión de batería avanzada- para maximizar la autonomía de autos eléctricos o híbridos.'),
		(91,'Flem','Conkie',21753071,'FConkie@mail.com',6,'Vehículo con cargador inalámbrico para dispositivos móviles- para una mayor comodidad y conectividad sin cables.'),
		(92,'Igor','Schwier',39009066,'ISchwier@mail.com',5,'Coche con sistema de dirección asistida eléctrica- para una maniobrabilidad más precisa y ahorro de combustible.'),
		(93,'Garik','Wort',41464167,'GWort@mail.com',9,'Auto con sistema de monitoreo de punto ciego- para ayudar a evitar accidentes al cambiar de carril o estacionar.'),
		(94,'Wood','Thomton',16814184,'WThomton@mail.com',7,'Auto con parabrisas calefactado- ideal para zonas frías donde la nieve o el hielo pueden afectar la visibilidad.'),
		(95,'Delila','Boundley',23092930,'DBoundley@mail.com',8,'Vehículo con sistema de sonido premium- para disfrutar de música y entretenimiento con la mejor calidad de audio.'),
		(96,'Wells','Crinkley',30673874,'WCrinkley@mail.com',7,'Vehículo con conectores USB para cargar dispositivos móviles y mantener la conectividad durante trayectos largos.'),
		(97,'Taylor','Ramelet',37637550,'TRamelet@mail.com',10,'Vehículo con cortinas laterales de aire- para mayor protección en caso de impactos laterales durante un accidente.'),
		(98,'Dottie','Wedlake',33822722,'DWedlake@mail.com',6,'Auto eléctrico con autonomía superior a 300 km- amigable con el medio ambiente y libre de emisiones contaminantes.'),
		(99,'Sherye','Forgie',19229977,'SForgie@mail.com',6,'Auto con sistema de control de estabilidad avanzada- para prevenir derrapes en superficies mojadas o resbaladizas.'),
		(100,'Sibeal','Kneeland',35074204,'SKneeland@mail.com',8,'Auto con puertas de cierre suave- que reducen el esfuerzo al cerrar y mejoran el confort en la experiencia de uso.'),
		(101,'Buckie','Lerohan',16530626,'BLerohan@mail.com',8,'Auto con asientos reclinables y climatización ajustable- para mayor confort en trayectos largos y climas extremos.'),
		(102,'Pavel','Drewell',16608708,'PDrewell@mail.com',9,'Vehículo con seguro contra todo riesgo incluido- para mayor tranquilidad del cliente en caso de accidentes o daños.'),
		(103,'Stearn','Walesa',33664861,'SWalesa@mail.com',8,'Vehículo con entrada sin llave y arranque a distancia- para mayor comodidad y seguridad al entrar y salir del auto.'),
		(104,'Mariska','Adrain',37495158,'MAdrain@mail.com',8,'Vehículo con capacidad de plegar asientos traseros- para aumentar el espacio de almacenamiento según sea necesario.'),
		(105,'Con','Longwood',34094773,'CLongwood@mail.com',6,'Vehículo con asientos calefaccionados en todas las plazas- ideal para climas fríos donde se necesita mayor confort.'),
		(106,'Samson','Enns',28672705,'SEnns@mail.com',9,'Auto con tecnología de frenado regenerativo- para aumentar la eficiencia energética en autos eléctricos o híbridos.'),
		(107,'Kelcey','Meert',22787046,'KMeert@mail.com',8,'Vehículo con sistema de estabilización de remolque- para mayor seguridad al conducir con cargas pesadas o caravanas.'),
		(108,'Ulysses','Kacheller',18912612,'UKacheller@mail.com',9,'Vehículo con faros automáticos y luces LED- para mejorar la visibilidad en carretera y proporcionar mayor seguridad.'),
		(109,'Phedra','Dyer',19830705,'PDyer@mail.com',9,'SUV con tracción en las cuatro ruedas- perfecto para trayectos off-road o terrenos irregulares- con mayor seguridad.'),
		(110,'Sarge','Bourgeois',16341640,'SBourgeois@mail.com',9,'Coche con sistema de asistencia de estacionamiento automático- para facilitar el aparcamiento en espacios reducidos.'),
		(111,'Clay','Gilmartin',22933116,'CGilmartin@mail.com',8,'Auto con llantas de bajo perfil- para una conducción más deportiva y mejor respuesta en carreteras de alta velocidad.'),
		(112,'Siouxie','Tufts',29689699,'STufts@mail.com',5,'Vehículo con sistema de visión nocturna- para mejorar la visibilidad durante la conducción en condiciones de baja luz.'),
		(113,'Yettie','De Luna',39181038,'YDe Luna@mail.com',6,'Vehículo con sistema de monitoreo de fatiga del conductor- para alertar sobre posibles signos de cansancio al volante.'),
		(114,'Teena','Tsarovic',24386015,'TTsarovic@mail.com',9,'Vehículo con pantalla táctil de alta resolución- para facilitar el acceso a controles de navegación y entretenimiento.'),
		(115,'Felic','Baxter',23592836,'FBaxter@mail.com',9,'Vehículo con capacidad para 7 pasajeros- ideal para viajes familiares o grupos grandes con amplio espacio de maletero.'),
		(116,'Say','Piggins',37994495,'SPiggins@mail.com',6,'Coche con sistema de protección contra vuelcos- para mayor seguridad en carreteras con curvas o terrenos accidentados.'),
		(117,'Romona','Darrach',15826729,'RDarrach@mail.com',7,'Auto híbrido con motor de combustión y eléctrico- para mayor eficiencia energética y ahorro en consumo de combustible.'),
		(118,'Vergil','Thompson',28487881,'VThompson@mail.com',8,'Auto con tecnología de asistencia para subidas- para evitar que el coche ruede hacia atrás en pendientes pronunciadas.'),
		(119,'Jilleen','Joy',19633264,'JJoy@mail.com',5,'Auto con sistema de reducción de emisiones- ideal para clientes preocupados por el impacto ambiental de sus trayectos.'),
		(120,'Tisha','Hodgets',15930680,'THodgets@mail.com',5,'Auto compacto para conducir en la ciudad- ideal para maniobras en espacios reducidos y con bajo consumo de combustible.'),
		(121,'Fredericka','Scanterbury',40943636,'FScanterbury@mail.com',9,'Coche con ventanas polarizadas- ideal para mayor privacidad y protección contra la luz solar intensa en climas cálidos.'),
		(122,'Harold','Bound',17184975,'HBound@mail.com',9,'Coche con cámaras de estacionamiento y sensores de proximidad- ideal para quienes desean mayor seguridad al estacionar.'),
		(123,'Cathy','Sabin',23024428,'CSabin@mail.com',5,'Auto con techo solar- para disfrutar de una mayor entrada de luz natural y una experiencia de conducción más placentera.'),
		(124,'Lexie','Goucher',17127623,'LGoucher@mail.com',6,'Vehículo con amplio espacio de maletero- ideal para transportar equipaje o grandes volúmenes en viajes largos o mudanzas.'),
		(125,'Chen','Andrag',41018496,'CAndrag@mail.com',5,'Auto con capacidad de remolque- perfecto para transportar caravanas- botes o cargas pesadas en viajes de larga distancia.'),
		(126,'Crystal','Burvill',44573516,'CBurvill@mail.com',7,'Auto con asistencia en carretera 24/7- para mayor seguridad en caso de averías o accidentes en cualquier momento del día.'),
		(127,'Catina','Bursell',32523406,'CBursell@mail.com',8,'Auto con tecnología de regeneración de energía en frenado- para maximizar la eficiencia en vehículos híbridos y eléctricos.'),
		(128,'Shawnee','Espinoy',29635085,'SEspinoy@mail.com',7,'Auto con capacidad para adaptar portaequipajes en el techo- ideal para quienes llevan equipos deportivos o grandes maletas.'),
		(129,'Dickie','Baud',29383610,'DBaud@mail.com',8,'Vehículo con iluminación ambiental personalizable- para crear una atmósfera única y agradable durante la conducción nocturna.'),
		(130,'Tamar','Gosby',25410552,'TGosby@mail.com',9,'Vehículo con frenos ABS y control de estabilidad- para garantizar mayor seguridad y control en condiciones adversas de manejo.'),
		(131,'Roselia','Adami',21369801,'RAdami@mail.com',6,'Vehículo con asientos para niños instalados- ideal para familias con bebés o niños pequeños que necesitan seguridad adicional.'),
		(132,'Ellary','Doubleday',17635391,'EDoubleday@mail.com',7,'Coche con conexión Bluetooth y sistemas de entretenimiento avanzados- para disfrutar de música y llamadas en trayectos largos.'),
		(133,'Timofei','Poon',30140282,'TPoon@mail.com',7,'Auto con tapicería resistente a manchas- ideal para quienes viajan con niños o mascotas y buscan un vehículo fácil de limpiar.'),
		(134,'Giselle','Barttrum',23823063,'GBarttrum@mail.com',10,'Auto deportivo con alta potencia- para los clientes que buscan una experiencia de conducción emocionante y de alto rendimiento.'),
		(135,'Rubina','Iczokvitz',16939720,'RIczokvitz@mail.com',9,'Coche de lujo con interior de cuero y tecnología avanzada- ideal para eventos especiales o clientes que buscan máxima comodidad.'),
		(136,'Benjamen','Comberbach',31408203,'BComberbach@mail.com',6,'Auto con sistema de purificación de aire- ideal para personas con alergias o quienes desean aire más limpio dentro del vehículo.'),
		(137,'Layla','Raxworthy',22810693,'LRaxworthy@mail.com',5,'Vehículo con GPS incorporado para facilitar la navegación en ciudades desconocidas o zonas rurales sin acceso a señal de celular.'),
		(138,'Whitman','McCrohon',30748757,'WMcCrohon@mail.com',6,'Auto con volante ajustable en altura y profundidad- para personalizar la posición de conducción según la preferencia del cliente.'),
		(139,'Onofredo','Chaudron',42969124,'OChaudron@mail.com',10,'Auto con control crucero adaptativo- para mantener una velocidad constante en la carretera sin necesidad de acelerar manualmente.'),
		(140,'Clair','Andriesse',33873056,'CAndriesse@mail.com',6,'Auto con asientos de ajuste eléctrico con memoria- para facilitar el cambio de conductores sin perder la configuración preferida.'),
		(141,'Carine','Simmonds',38095319,'CSimmonds@mail.com',6,'Vehículo con parabrisas acústico- para reducir el ruido exterior y mejorar el confort de conducción en áreas urbanas o autopistas.'),
		(142,'Rory','Oldroyde',17425496,'ROldroyde@mail.com',10,'Coche con sistema de control de presión de neumáticos- para alertar sobre posibles problemas en las ruedas y mejorar la seguridad.'),
		(143,'Baudoin','Wogan',44240985,'BWogan@mail.com',7,'Coche con sistema de alerta de colisión frontal- para mayor seguridad en caso de acercarse demasiado a otro vehículo en carretera.'),
		(144,'Melissa','Prescote',23260065,'MPrescote@mail.com',7,'Vehículo con sistema de tracción inteligente- para mayor control en terrenos resbaladizos o durante condiciones climáticas adversas.'),
		(145,'Agretha','Espinha',38470763,'AEspinha@mail.com',7,'Vehículo con transmisión automática- para facilitar la conducción y evitar el cansancio en trayectos largos en la ciudad o carretera.'),
		(146,'Reidar','O Hear',15155407,'ROHear@mail.com',6,'Vehículo con sistemas de asistencia de conducción- como alerta de cambio de carril y frenado automático en situaciones de emergencia.'),
		(147,'Anselma','Shovlar',37728237,'AShovlar@mail.com',6,'Vehículo con capacidad para integrar aplicaciones móviles- como Apple CarPlay o Android Auto- para una experiencia de manejo conectada.'),
		(148,'Fidel','Smelley',30249569,'FSmelley@mail.com',8,'Vehículo con sistema de climatización dual- para que tanto el conductor como el pasajero puedan ajustar la temperatura a su preferencia.'),
		(149,'Horten','Cook',21250961,'HCook@mail.com',7,'Coche con sistema de advertencia de tráfico cruzado trasero- para mayor seguridad al retroceder en estacionamientos o calles concurridas.'),
		(150,'Nickie','Heppner',38402343,'NHeppner@mail.com',7,'Auto con sistema de reconocimiento de señales de tráfico- para alertar al conductor sobre cambios en los límites de velocidad o advertencias.'),
		(151,'Melina','Nunson',32193954,'MNunson@mail.com',8,'Auto con sistema de reconocimiento de señales de tráfico- para alertar al conductor sobre cambios en los límites de velocidad o advertencias.'),
		(152,'Kenton','Dies',43404289,'KDies@mail.com',7,'Coche con sistema de advertencia de tráfico cruzado trasero- para mayor seguridad al retroceder en estacionamientos o calles concurridas.'),
		(153,'Nert','Marcoolyn',15906607,'NMarcoolyn@mail.com',6,'Vehículo con sistema de climatización dual- para que tanto el conductor como el pasajero puedan ajustar la temperatura a su preferencia.'),
		(154,'Angelo','Boldecke',19679859,'ABoldecke@mail.com',9,'Vehículo con capacidad para integrar aplicaciones móviles- como Apple CarPlay o Android Auto- para una experiencia de manejo conectada.'),
		(155,'Tomkin','Mattiello',35153288,'TMattiello@mail.com',5,'Vehículo con transmisión automática- para facilitar la conducción y evitar el cansancio en trayectos largos en la ciudad o carretera.'),
		(156,'Ketty','Boggers',41821638,'KBoggers@mail.com',6,'Vehículo con sistemas de asistencia de conducción- como alerta de cambio de carril y frenado automático en situaciones de emergencia.'),
		(157,'Cindy','Byfford',34670825,'CByfford@mail.com',6,'Vehículo con sistema de tracción inteligente- para mayor control en terrenos resbaladizos o durante condiciones climáticas adversas.'),
		(158,'Lucky','Thoday',36526061,'LThoday@mail.com',8,'Vehículo con parabrisas acústico- para reducir el ruido exterior y mejorar el confort de conducción en áreas urbanas o autopistas.'),
		(159,'Stearne','D Almeida',33984714,'SDAlmeida@mail.com',6,'Coche con sistema de control de presión de neumáticos- para alertar sobre posibles problemas en las ruedas y mejorar la seguridad.'),
		(160,'Leon','Van Velde',19067439,'LVan Velde@mail.com',7,'Coche con sistema de alerta de colisión frontal- para mayor seguridad en caso de acercarse demasiado a otro vehículo en carretera.'),
		(161,'Corina','Dionisetti',23439332,'CDionisetti@mail.com',9,'Vehículo con GPS incorporado para facilitar la navegación en ciudades desconocidas o zonas rurales sin acceso a señal de celular.'),
		(162,'Gwynne','Langtry',41679674,'GLangtry@mail.com',8,'Auto con volante ajustable en altura y profundidad- para personalizar la posición de conducción según la preferencia del cliente.'),
		(163,'Osbourne','Pickthorn',36617053,'OPickthorn@mail.com',8,'Auto con control crucero adaptativo- para mantener una velocidad constante en la carretera sin necesidad de acelerar manualmente.'),
		(164,'Carole','Ellingford',36356382,'CEllingford@mail.com',8,'Auto con asientos de ajuste eléctrico con memoria- para facilitar el cambio de conductores sin perder la configuración preferida.'),
		(165,'Rog','Iacovini',29826176,'RIacovini@mail.com',5,'Coche de lujo con interior de cuero y tecnología avanzada- ideal para eventos especiales o clientes que buscan máxima comodidad.'),
		(166,'Trula','Knotton',38160169,'TKnotton@mail.com',6,'Auto con sistema de purificación de aire- ideal para personas con alergias o quienes desean aire más limpio dentro del vehículo.'),
		(167,'Jemmy','Aveline',31512656,'JAveline@mail.com',9,'Auto deportivo con alta potencia- para los clientes que buscan una experiencia de conducción emocionante y de alto rendimiento.'),
		(168,'Katya','Riddington',37122295,'KRiddington@mail.com',9,'Vehículo con frenos ABS y control de estabilidad- para garantizar mayor seguridad y control en condiciones adversas de manejo.'),
		(169,'Neddie','Joliffe',18932138,'NJoliffe@mail.com',5,'Vehículo con asientos para niños instalados- ideal para familias con bebés o niños pequeños que necesitan seguridad adicional.'),
		(170,'Humphrey','Bromage',28328107,'HBromage@mail.com',10,'Coche con conexión Bluetooth y sistemas de entretenimiento avanzados- para disfrutar de música y llamadas en trayectos largos.'),
		(171,'Gypsy','Eburne',31793190,'GEburne@mail.com',7,'Auto con tapicería resistente a manchas- ideal para quienes viajan con niños o mascotas y buscan un vehículo fácil de limpiar.'),
		(172,'Sonny','Meekings',42032923,'SMeekings@mail.com',5,'Vehículo con iluminación ambiental personalizable- para crear una atmósfera única y agradable durante la conducción nocturna.'),
		(173,'Marian','Limer',43385008,'MLimer@mail.com',7,'Auto con tecnología de regeneración de energía en frenado- para maximizar la eficiencia en vehículos híbridos y eléctricos.'),
		(174,'Sam','Franzolini',17073606,'SFranzolini@mail.com',8,'Auto con capacidad para adaptar portaequipajes en el techo- ideal para quienes llevan equipos deportivos o grandes maletas.'),
		(175,'Natividad','Sussans',30530853,'NSussans@mail.com',5,'Vehículo con amplio espacio de maletero- ideal para transportar equipaje o grandes volúmenes en viajes largos o mudanzas.'),
		(176,'Shepard','Cubley',43945624,'SCubley@mail.com',9,'Auto con capacidad de remolque- perfecto para transportar caravanas- botes o cargas pesadas en viajes de larga distancia.'),
		(177,'Vanna','Grocock',42799953,'VGrocock@mail.com',9,'Auto con asistencia en carretera 24/7- para mayor seguridad en caso de averías o accidentes en cualquier momento del día.'),
		(178,'Anabelle','Ziem',31679793,'AZiem@mail.com',10,'Auto con techo solar- para disfrutar de una mayor entrada de luz natural y una experiencia de conducción más placentera.'),
		(179,'Basia','Padrick',33260455,'BPadrick@mail.com',6,'Auto compacto para conducir en la ciudad- ideal para maniobras en espacios reducidos y con bajo consumo de combustible.'),
		(180,'Abram','Matteacci',33916876,'AMatteacci@mail.com',7,'Coche con ventanas polarizadas- ideal para mayor privacidad y protección contra la luz solar intensa en climas cálidos.'),
		(181,'Jayme','Mauser',26369314,'JMauser@mail.com',6,'Coche con cámaras de estacionamiento y sensores de proximidad- ideal para quienes desean mayor seguridad al estacionar.'),
		(182,'Weidar','Stonier',42098044,'WStonier@mail.com',5,'Vehículo con sistema de visión nocturna- para mejorar la visibilidad durante la conducción en condiciones de baja luz.'),
		(183,'Josy','Van Dijk',23980327,'JVan Dijk@mail.com',8,'Vehículo con sistema de monitoreo de fatiga del conductor- para alertar sobre posibles signos de cansancio al volante.'),
		(184,'Boonie','Mougenel',39966693,'BMougenel@mail.com',7,'Vehículo con pantalla táctil de alta resolución- para facilitar el acceso a controles de navegación y entretenimiento.'),
		(185,'Norine','Frenzel',17452983,'Nfrenzel@mail.com',7,'Vehículo con capacidad para 7 pasajeros- ideal para viajes familiares o grupos grandes con amplio espacio de maletero.'),
		(186,'Lilyan','Pomroy',19871396,'lpomroy55@biglobe.ne.jp',9,'Coche con sistema de protección contra vuelcos- para mayor seguridad en carreteras con curvas o terrenos accidentados.'),
		(187,'Vivienne','Druce',34107560,'vdruce56@wikipedia.org',6,'Auto híbrido con motor de combustión y eléctrico- para mayor eficiencia energética y ahorro en consumo de combustible.'),
		(188,'Maris','Cisson',32668689,'mcisson57@flavors.me',7,'Auto con tecnología de asistencia para subidas- para evitar que el coche ruede hacia atrás en pendientes pronunciadas.'),
		(189,'Ira','Ibotson',35893188,'iibotson58@wisc.edu',8,'Auto con sistema de reducción de emisiones- ideal para clientes preocupados por el impacto ambiental de sus trayectos.'),
		(190,'Letisha','Tolmie',33697530,'ltolmie59@nhs.uk',7,'Auto con llantas de bajo perfil- para una conducción más deportiva y mejor respuesta en carreteras de alta velocidad.'),
		(191,'Juliet','Whiteland',21353341,'jwhiteland5a@cnbc.com',6,'Vehículo con sistema de estabilización de remolque- para mayor seguridad al conducir con cargas pesadas o caravanas.'),
		(192,'Rebeka','Melmeth',36987449,'rmelmeth5b@cdbaby.com',6,'Vehículo con faros automáticos y luces LED- para mejorar la visibilidad en carretera y proporcionar mayor seguridad.'),
		(193,'Mikel','Hannen',27482670,'mhannen5c@joomla.org',6,'SUV con tracción en las cuatro ruedas- perfecto para trayectos off-road o terrenos irregulares- con mayor seguridad.'),
		(194,'Virgilio','Shaughnessy',37427938,'vshaughnessy5d@amazon.co.uk',6,'Coche con sistema de asistencia de estacionamiento automático- para facilitar el aparcamiento en espacios reducidos.'),
		(195,'Westbrook','Zanussii',44985693,'wzanussii5e@accuweather.com',9,'Vehículo con seguro contra todo riesgo incluido- para mayor tranquilidad del cliente en caso de accidentes o daños.'),
		(196,'Moria','Parres',31108909,'mparres5f@bloglines.com',8,'Vehículo con entrada sin llave y arranque a distancia- para mayor comodidad y seguridad al entrar y salir del auto.'),
		(197,'Samara','Stansbie',34749281,'sstansbie5g@canalblog.com',7,'Vehículo con capacidad de plegar asientos traseros- para aumentar el espacio de almacenamiento según sea necesario.'),
		(198,'Emmey','Dessaur',27621745,'edessaur5h@omniture.com',7,'Vehículo con asientos calefaccionados en todas las plazas- ideal para climas fríos donde se necesita mayor confort.'),
		(199,'Cameron','Bosenworth',22262911,'cbosenworth5i@census.gov',8,'Auto con tecnología de frenado regenerativo- para aumentar la eficiencia energética en autos eléctricos o híbridos.'),
		(200,'Kaleb','Crier',43424098,'kcrier5j@answers.com',9,'Vehículo con cortinas laterales de aire- para mayor protección en caso de impactos laterales durante un accidente.'),
		(201,'Shayne','Spicer',19227616,'sspicer5k@bing.com',5,'Auto eléctrico con autonomía superior a 300 km- amigable con el medio ambiente y libre de emisiones contaminantes.'),
		(202,'Margo','Flann',34420710,'mflann5l@php.net',7,'Auto con sistema de control de estabilidad avanzada- para prevenir derrapes en superficies mojadas o resbaladizas.'),
		(203,'Benji','Swaile',30648860,'bswaile5m@nasa.gov',9,'Auto con puertas de cierre suave- que reducen el esfuerzo al cerrar y mejoran el confort en la experiencia de uso.'),
		(204,'Caro','Cartwright',25238040,'ccartwright5n@studiopress.com',7,'Auto con asientos reclinables y climatización ajustable- para mayor confort en trayectos largos y climas extremos.'),
		(205,'Madelina','Kimmins',33856643,'mkimmins5o@studiopress.com',9,'Vehículo con sistema de sonido premium- para disfrutar de música y entretenimiento con la mejor calidad de audio.'),
		(206,'Dorian','Hazelden',24917079,'dhazelden5p@accuweather.com',9,'Vehículo con conectores USB para cargar dispositivos móviles y mantener la conectividad durante trayectos largos.'),
		(207,'Silvain','Losty',28816933,'slosty5q@surveymonkey.com',9,'Vehículo con sistema de insonorización mejorado- para una experiencia de conducción más silenciosa y placentera.'),
		(208,'Crin','Lowater',23646841,'clowater5r@so-net.ne.jp',6,'Vehículo con sistema de gestión de batería avanzada- para maximizar la autonomía de autos eléctricos o híbridos.'),
		(209,'Quincey','Falcus',15144362,'qfalcus5s@vistaprint.com',10,'Vehículo con cargador inalámbrico para dispositivos móviles- para una mayor comodidad y conectividad sin cables.'),
		(210,'Daveen','Vel',15834570,'dvel5t@google.com.au',8,'Coche con sistema de dirección asistida eléctrica- para una maniobrabilidad más precisa y ahorro de combustible.'),
		(211,'Valenka','Sandercock',35451794,'vsandercock5u@wired.com',8,'Auto con sistema de monitoreo de punto ciego- para ayudar a evitar accidentes al cambiar de carril o estacionar.'),
		(212,'Vanessa','Stirton',25391906,'vstirton5v@cpanel.net',7,'Auto con parabrisas calefactado- ideal para zonas frías donde la nieve o el hielo pueden afectar la visibilidad.'),
		(213,'Betteanne','Doddemeede',22282111,'bdoddemeede5w@wunderground.com',7,'Auto con suspensión deportiva- para una experiencia de conducción más dinámica y ágil en carreteras con curvas.'),
		(214,'Duncan','Wrankling',21470221,'dwrankling5x@berkeley.edu',6,'Auto con función de autoaparado- para mayor seguridad en zonas con mucho tráfico o durante maniobras complejas.'),
		(215,'Sissie','Robinette',31862449,'srobinette5y@comcast.net',6,'Vehículo con freno de mano electrónico- para mayor facilidad y seguridad al estacionar en diferentes terrenos.'),
		(216,'Oralle','Sawforde',23401643,'osawforde5z@cam.ac.uk',10,'Coche con limitador de velocidad ajustable- para evitar superar los límites de velocidad en zonas controladas.'),
		(217,'Amandie','Julian',25370047,'ajulian60@webmd.com',8,'Auto con sistema de frenado automático en reversa- para evitar colisiones al retroceder en espacios ajustados.'),
		(218,'Jinny','Snary',41180046,'jsnary61@tiny.cc',6,'Vehículo con luces adaptativas- que ajustan el haz de luz según las condiciones de la carretera y el entorno.'),
		(219,'Dalis','Hentzer',25488953,'dhentzer62@a8.net',9,'Coche con sistemas de ahorro de combustible- como el apagado automático del motor en detenciones prolongadas.'),
		(220,'Luce','Gytesham',33237820,'lgytesham63@dailymotion.com',6,'Vehículo con llantas todo terreno- para trayectos fuera de la carretera o en superficies con baja tracción.'),
		(221,'Wayne','Forward',36608081,'wforward64@archive.org',10,'Vehículo con asientos ventilados- ideal para climas cálidos donde el cuero o la tela pueden acumular calor.'),
		(222,'Zulema','Issatt',32755818,'zissatt65@tripadvisor.com',7,'Auto con espejos retrovisores ajustables electrónicamente- para mayor comodidad y visibilidad al conducir.'),
		(223,'Ermengarde','Bardell',18301907,'ebardell66@youtu.be',8,'Coche con tapicería de cuero perforado- para una mejor ventilación y confort en climas cálidos o fríos.'),
		(224,'Olivette','Cogley',20641512,'ocogley67@infoseek.co.jp',7,'Auto con espejos retrovisores con calefacción- para evitar que se empañen en climas fríos o lluviosos.'),
		(225,'Bucky','Dalziel',16506432,'bdalziel68@usatoday.com',7,'Auto con capacidad para adaptar una silla de ruedas o espacio para personas con movilidad reducida.'),
		(226,'Nat','Pendlenton',33261871,'npendlenton69@chronoengine.com',8,'Vehículo con cortinas laterales de aire- para mayor protección en caso de impactos laterales durante un accidente.'),
		(227,'Allx','Klaaassen',25667298,'aklaaassen6a@arizona.edu',9,'Auto eléctrico con autonomía superior a 300 km- amigable con el medio ambiente y libre de emisiones contaminantes.'),
		(228,'Wald','Sweeten',42220359,'wsweeten6b@nbcnews.com',9,'Auto con sistema de control de estabilidad avanzada- para prevenir derrapes en superficies mojadas o resbaladizas.'),
		(229,'Ethelind','Haward',37811663,'ehaward6c@joomla.org',6,'Auto con puertas de cierre suave- que reducen el esfuerzo al cerrar y mejoran el confort en la experiencia de uso.'),
		(230,'Fae','Trusler',19028938,'ftrusler6d@boston.com',10,'Auto con asientos reclinables y climatización ajustable- para mayor confort en trayectos largos y climas extremos.'),
		(231,'Celeste','Jacobowitz',17274969,'cjacobowitz6e@marriott.com',6,'Vehículo con sistema de sonido premium- para disfrutar de música y entretenimiento con la mejor calidad de audio.'),
		(232,'Winnah','Pharoah',23585355,'wpharoah6f@fc2.com',8,'Vehículo con conectores USB para cargar dispositivos móviles y mantener la conectividad durante trayectos largos.'),
		(233,'Myrah','Hove',31517810,'mhove6g@reference.com',7,'Vehículo con sistema de insonorización mejorado- para una experiencia de conducción más silenciosa y placentera.'),
		(234,'Martin','Grundey',40321359,'mgrundey6h@reuters.com',8,'Vehículo con sistema de gestión de batería avanzada- para maximizar la autonomía de autos eléctricos o híbridos.'),
		(235,'Merralee','Toolan',39847949,'mtoolan6i@newyorker.com',7,'Vehículo con cargador inalámbrico para dispositivos móviles- para una mayor comodidad y conectividad sin cables.'),
		(236,'Dyanne','Totaro',40028764,'dtotaro6j@hugedomains.com',7,'Coche con sistema de dirección asistida eléctrica- para una maniobrabilidad más precisa y ahorro de combustible.'),
		(237,'Ivette','Rainon',37529681,'irainon6k@nydailynews.com',8,'Auto con sistema de monitoreo de punto ciego- para ayudar a evitar accidentes al cambiar de carril o estacionar.'),
		(238,'Worthington','Ruddock',28170797,'wruddock6l@flavors.me',8,'Auto con parabrisas calefactado- ideal para zonas frías donde la nieve o el hielo pueden afectar la visibilidad.'),
		(239,'Lezley','Droghan',28378099,'ldroghan6m@paginegialle.it',9,'Auto con suspensión deportiva- para una experiencia de conducción más dinámica y ágil en carreteras con curvas.'),
		(240,'Nathanael','Boulter',35088917,'nboulter6n@forbes.com',9,'Auto con función de autoaparado- para mayor seguridad en zonas con mucho tráfico o durante maniobras complejas.'),
		(241,'Margarita','Gilbody',21911244,'mgilbody6o@mit.edu',10,'Vehículo con freno de mano electrónico- para mayor facilidad y seguridad al estacionar en diferentes terrenos.'),
		(242,'Theresita','Ellesworthe',25802646,'tellesworthe6p@ehow.com',5,'Coche con limitador de velocidad ajustable- para evitar superar los límites de velocidad en zonas controladas.'),
		(243,'Kean','Ludmann',32272978,'kludmann6q@dot.gov',9,'Auto con sistema de frenado automático en reversa- para evitar colisiones al retroceder en espacios ajustados.'),
		(244,'Rodina','O Deoran',23895109,'rodeoran6r@1und1.de',9,'Vehículo con luces adaptativas- que ajustan el haz de luz según las condiciones de la carretera y el entorno.'),
		(245,'Brok','Capewell',16271538,'bcapewell6s@yellowbook.com',9,'Coche con sistemas de ahorro de combustible- como el apagado automático del motor en detenciones prolongadas.'),
		(246,'Samuele','Sigsworth',32543112,'ssigsworth6t@youtu.be',6,'Vehículo con llantas todo terreno- para trayectos fuera de la carretera o en superficies con baja tracción.'),
		(247,'Kat','Kirkwood',26036174,'kkirkwood6u@discovery.com',7,'Vehículo con asientos ventilados- ideal para climas cálidos donde el cuero o la tela pueden acumular calor.'),
		(248,'Tuckie','Duham',30688069,'tduham6v@4shared.com',8,'Auto con espejos retrovisores ajustables electrónicamente- para mayor comodidad y visibilidad al conducir.'),
		(249,'Lynett','Diviny',40111494,'ldiviny6w@tumblr.com',8,'Coche con tapicería de cuero perforado- para una mejor ventilación y confort en climas cálidos o fríos.'),
		(250,'Fredrick','Spaughton',32951806,'fspaughton6x@sbwire.com',10,'Auto con espejos retrovisores con calefacción- para evitar que se empañen en climas fríos o lluviosos.')
        ;